### ISSUE TITLE
SpacePrez Expand Geometry button not working properly

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#11]
e.g on https://linked.fsdf.org.au/dataset/electrical-infrastructure/collections/TL/items/101

When mouse hovering on the Expand button in a feature's geometry part, the button is only activated by hovering on the left corner of the button instead of anywhere on the button.

This goes away for "Collapse" which is clickable as normal

As tested, this problem only happens to the power station and transmission line feature collections.

![image](https://user-images.githubusercontent.com/7321872/186414442-b45414ac-e8d1-448e-8d44-89710bd8624c.png)

**Comment by recalcitrantsupplant** [comment]
Re. raise in FE repo if issues still present w/ Vue.js app.
