### ISSUE TITLE
Listing endpoints for non-"top-level" items are not limited/paginated

### ISSUE THREAD

**Issue by jamiefeiss** [RDFLib/prez#111]
See https://data.idnau.org/s/datasets/pid:atns/collections/atns:entity-areas/items for example. Normally, a listing page should be limited to 20 results.

The issue seems to be that the LIMIT statement at line 124 below is not used when `focus_item.top_level_listing` is blank, i.e. when focused on a non-top-level object, like a feature collection listing features.

The query of interest is in `object_listings.py` below:
https://github.com/RDFLib/prez/blob/bcb9769d2d931075e2188fdd830679ea349e5b11/prez/sparql/objects_listings.py#L90-L127

**Comment by edmondchuc** [comment]
Related issue: https://github.com/RDFLib/prez/issues/109
Related PR: https://github.com/RDFLib/prez/pull/110
