### ISSUE TITLE
Simple fix for duplicate results with multiple flavours with same SPARQL endpoint

### ISSUE THREAD

**Issue by jamiefeiss** [RDFLib/prez#113]
Just putting this up as a suggestion to solve this problem in the short term, as this issue affects multiple IDN tools, including Prez UI in general.

At lines 42 & 108 of `routers/sparql.py`:
```python
endpoints = {p: settings.sparql_creds[p]["endpoint"] for p in settings.enabled_prezs}
unique_endpoints = {}
for p, endpoint in endpoints.items():
    if endpoint not in unique_endpoints.values():
        unique_endpoints[p] = endpoint
results = await asyncio.gather(
    *[sparql_query(query, p) for p in unique_endpoints.keys()]
)
```

I know this solution doesn't accurately show which subsystem returned the results, but the results would come from the same endpoint anyway, and fixing the duplicate results I think is much more important than correctly returning the endpoint info.

Happy to discuss further and make a PR if preferred.

**Comment by nicholascar** [comment]
Test comment
