### ISSUE TITLE
Document expected behaviour of profiles

### ISSUE THREAD

**Issue by recalcitrantsupplant** [RDFLib/prez#122]
For included, excluded, sequence, inverse paths, and the listing predicates what is the expected behaviour and allowable combinations.

For object predicates: (sh:path, dash:hidden, sh:sequencePath, sh:inversePath)
- include or exclude are mandatory and exclusive, both cannot be specified (sh:path or sh:path + dash:hidden)
- sh:sequencePath and sh:inversePath are optional includes.
- sequence paths where the first predicate is excluded should not be returned. (?)

For listing predicates:
- the system should return a minimal set of paginated results
- the system should return the union of all objects related to the focus item (or general class) via **one or more** listing predicates.
(in the case of listing endpoints, only one type of listing predicate is configured in the system)
- where the system is listing items in the "item" or "object" pages, included/excluded predicates specified for the object should be ignored. For example if rdfs:member is not included via sh:path, or is excluded via dash:hidden, and a listing predicate specifies rdfs:member, the results for the listing predicate should still be returned.

**Comment by recalcitrantsupplant** [comment]
draft - please provide feedback @nicholascar @edmondchuc @hjohns

**Comment by edmondchuc** [comment]
Is this for user-facing documentation on how to configure Prez or is this an internal design discussion on the behaviours of Prez?

**Comment by recalcitrantsupplant** [comment]
internal design first

**Comment by hjohns** [comment]
Design document required:
- Outline of current state?
- Target state design
- Capture flow (@recalcitrantsupplant)
- Cookbook documentation with recipes (additional scenarios to new doco)

**Comment by recalcitrantsupplant** [comment]
going to push this issue to next week

**Comment by recalcitrantsupplant** [comment]
https://lucid.app/lucidchart/b5660138-0e38-427b-aab4-18eb4c4b73cb/edit?viewport_loc=-80%2C-302%2C2269%2C1137%2C0_0&invitationId=inv_76a1d32b-5fbf-4c39-ace5-85152cb3f69f

**Comment by edmondchuc** [comment]
David to add some examples to dev readme and add the diagrams from Lucid to the dev readme. Two Lucid chart diagrams related to this will be merged into one.

**Comment by edmondchuc** [comment]
I think it would be good if we all add our current use cases and how we are using profiles to establish a common set of behaviours that need to be supported.

For example, in some of the projects I'm working on, I need `reg:status` and `schema:color` to appear in both the listing and object pages.

Once we have a set of use cases, we can then document how the profiles syntax cater for these use cases by using the available predicates (e.g., `alt-ext:otherAnnotationProps`, etc.).
