### ISSUE TITLE
Incorrect pagination of vocabularies

### ISSUE THREAD

**Issue by avillar** [RDFLib/prez#123]
I have a instance running at http://defs-dev.opengis.net/prez-hosted/v/vocab

It shows 13 pages of vocabularies, but anything past page 7 is empty.

SPARQL endpoint can be found at http://defs-dev.opengis.net:8261/fuseki-hosted/sparql

**Comment by recalcitrantsupplant** [comment]
@avillar could you confirm if this is still an issue w/ v4? (or v3 if you're still using it for that case, we can do a bugfix there too)

**Comment by avillar** [comment]
@recalcitrantsupplant I think v4 (using @hjohns's alpha branch) works correctly. I'd consider this issue deprecated (I'm not sure which status this deployment is in).
