### ISSUE TITLE
Default GeoSPARQL Profile missing for FeatureCollection

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#13]
We should be seeing a _GeoSPARQL_ profile as well as _OGC API Features_ and _Alternates_ and the _GeoSPARQL_ profile should have HTML (the same as OGC API Features) but, critically, also RDF/Turtle.

Without this, there is no basic RDF.

![image](https://user-images.githubusercontent.com/7321872/186415704-7ebf0c1e-d8ee-4a7d-b227-10024608011e.png)

https://geofabric.linked.fsdf.org.au/dataset/geofabric/collections/catchments
https://linked.fsdf.org.au/dataset/placenames/collections/places

Fine for Dataset:

https://geofabric.linked.fsdf.org.au/dataset/geofabric

Fine for Feature:

https://geofabric.linked.fsdf.org.au/dataset/geofabric/collections/catchments/items/43677381

**Comment by recalcitrantsupplant** [comment]
This has been added to Prez 4
