### ISSUE TITLE
Add API support to load large vocabularies with many concepts

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/prez#131]
This API will allow vocabularies of any number of concepts to be loaded and viewed by a client such as [prez-ui](https://github.com/RDFLib/prez-ui).

For clarification, this is for loading large vocabularies with the number of concepts in the 10s of thousands in a complex hierarchical manner, not for loading the listing of vocabularies page.

Related issues:

- https://github.com/RDFLib/prez-ui/issues/64

Considerations:
- Use the existing functionality within Prez to fetch labels using the predicates defined in the Prez system profiles.
- Use of `LIMIT` and `OFFSET` must be supported to support client-side infinite scrolling or paginated views.
- The design does not consider resources with multiple labels.
- The APIs use a new predicate in the `prez` namespace. `prez:childrenCount` (`xsd:integer`) indicates the count of child objects.

Other notes: our goal with this API is to create a scalable vocabulary API that can load and render vocabularies of any size. The techniques and patterns we use to perform infinite scrolling and incremental loading of narrower concepts can be applied more generally to the `/objects` endpoint in the future, but for now, let's just get vocabularies working first.

### GET `/v/vocab/{concept_scheme_curie}`

Get a SKOS Concept Scheme.

This retrieves everything about a Concept Scheme except for `skos:hasTopConcept`. Concepts that have `skos:inScheme` and `skos:topConceptOf` with values pointing to the Concept Scheme are also excluded.

#### Prez query request to database:

- The maximum blank node depth must be calculated and templated into the query.
- The variable `?p` applies a filter to filter out all `skos:hasTopConcept` values.
- The value bound to `?iri` is templated into the query.

```sparql
PREFIX prez: <https://prez.dev/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {  
  ?iri ?p ?o .

  # Blank node depth of 1
  ?iri ?p0 ?o0 .
  ?o0 ?p1 ?o1 .

  ?iri prez:childrenCount ?childrenCount .
}
WHERE {
  BIND(<http://linked.data.gov.au/def/borehole-status> as ?iri)
  ?iri ?p ?o .
  FILTER (?p != skos:hasTopConcept)

  {
    SELECT (COUNT(?topConcept) AS ?childrenCount)
    WHERE {
      BIND(<http://linked.data.gov.au/def/borehole-status> as ?iri)
      ?iri skos:hasTopConcept ?topConcept .
    }
  }

  # Blank node depth of 1
  ?iri ?p0 ?o0 .
  ?o0 ?p1 ?o1 .
  filter (isBlank(?o0))
}
```

#### Response:

```turtle
PREFIX agldwgstatus: <https://linked.data.gov.au/def/reg-statuses/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX prez: <https://prez.dev/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX reg: <http://purl.org/linked-data/registry#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

<http://linked.data.gov.au/def/borehole-status>
    a skos:ConceptScheme ;
    dcterms:created "2023-04-26"^^xsd:date ;
    dcterms:creator <https://linked.data.gov.au/org/gsq> ;
    dcterms:identifier "def:borehole-status"^^prez:slug ;
    dcterms:modified "2023-05-11"^^xsd:date ;
    dcterms:provenance "Compiled by the Geological Survey of Queensland for the Government Geoscience Information Committee (GGIC) in a Borehole Information Harmonisation Initiative in 2023" ;
    dcterms:publisher <https://linked.data.gov.au/org/gsq> ;
    reg:status agldwgstatus:experimental ;
    skos:definition "The current state of a borehole within its lifecycle from proposed through operational through to abandoned. Borehole status also applies to wells or boreholes comprised of multiple wellbores."@en ;
    skos:prefLabel "Borehole Status"@en ;
    prov:qualifiedDerivation [
            prov:entity <http://linked.data.gov.au/def/site-status> ;
            prov:hadRole <http://linked.data.gov.au/def/vocab-derivation-modes/subsetting-and-extension>
        ] ;
    prez:childrenCount 3 ;
.
```

---

### GET `/v/vocab/{concept_scheme_curie}/top-concepts`

Get a SKOS Concept Scheme's top concepts.

#### Query parameters:

- `page` - the result page, defaults to 1.
- `per_page` - the size of the page, defaults to 20.

#### Prez query:

- The value bound to `?iri` is templated into the query.
- An inner select query facilitates pagination and the query parameters `page` and `per_page` are translated to `LIMIT` and `OFFSET`.
- Look up vocabulary profile to determine label predicate.

```sparql
PREFIX prez: <https://prez.dev/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?concept skos:prefLabel ?label .
  ?iri prez:childrenCount ?childrenCount .
}
WHERE {
  BIND(<http://linked.data.gov.au/def/borehole-status> as ?iri)
  ?concept skos:prefLabel ?label .

  {
    SELECT (COUNT(?childConcept) AS ?childrenCount)
    WHERE {
      BIND(<http://linked.data.gov.au/def/borehole-status> as ?iri)
      ?iri skos:hasTopConcept ?childConcept .
    }
  }

  {
    SELECT ?concept
    WHERE {
      BIND(<http://linked.data.gov.au/def/borehole-status> as ?iri)
      ?iri skos:hasTopConcept ?concept .
      ?concept skos:prefLabel ?label .
    }
    ORDER BY ?label
    LIMIT 20
    OFFSET 0
  }
}
```

#### Response:

```turtle
PREFIX prez: <https://prez.dev/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

<http://linked.data.gov.au/def/borehole-status>
    prez:childrenCount 3 ;
.

<http://linked.data.gov.au/def/borehole-status/not-operational>
    skos:prefLabel "Not Operational"@en ;
.

<http://linked.data.gov.au/def/borehole-status/operational>
    skos:prefLabel "Operational"@en ;
.

<http://linked.data.gov.au/def/borehole-status/unknown>
    skos:prefLabel "Unknown"@en ;
.
```

---

### GET `/v/concept/{concept_curie}/narrowers`

Get a SKOS Concept's narrower concepts.

#### Query parameters:

- `page` - the result page, defaults to 1.
- `per_page` - the size of the page, defaults to 20.

#### Prez query:

- The value bound to `?iri` is templated into the query.
- An inner select query facilitates pagination and the query parameters `page` and `per_page` are translated to `LIMIT` and `OFFSET`.
- Look up vocabulary profile to determine label predicate.

```sparql
PREFIX prez: <https://prez.dev/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?concept skos:prefLabel ?label .
  ?iri prez:childrenCount ?childrenCount .
}
WHERE {
  BIND(<http://linked.data.gov.au/def/borehole-status/not-operational> as ?iri)
  ?concept skos:prefLabel ?label .

  {
    SELECT (COUNT(?childConcept) AS ?childrenCount)
    WHERE {
      BIND(<http://linked.data.gov.au/def/borehole-status/not-operational> as ?iri)
      ?childConcept skos:broader ?iri .
    }
  }

  {
    SELECT ?concept
    where {
      BIND(<http://linked.data.gov.au/def/borehole-status/not-operational> as ?iri)
      ?concept skos:broader ?iri .
      ?concept skos:prefLabel ?label .
    }
    ORDER BY ?label
    LIMIT 20
    OFFSET 0
  }
}
```

#### Response:

```turtle
PREFIX prez: <https://prez.dev/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

<http://linked.data.gov.au/def/borehole-status/capped>
    skos:prefLabel "Capped"@en ;
.

<http://linked.data.gov.au/def/borehole-status/cased-and-suspended>
    skos:prefLabel "Cased and Suspended"@en ;
.

<http://linked.data.gov.au/def/borehole-status/casing-removed>
    skos:prefLabel "Casing Removed"@en ;
.

<http://linked.data.gov.au/def/borehole-status/cemented>
    skos:prefLabel "Cemented"@en ;
.

<http://linked.data.gov.au/def/borehole-status/drilling-completed>
    skos:prefLabel "Drilling Completed"@en ;
.

<http://linked.data.gov.au/def/borehole-status/hazard-in-borehole>
    skos:prefLabel "Hazard in Borehole"@en ;
.

<http://linked.data.gov.au/def/borehole-status/not-operational>
    prez:childrenCount 10 ;
.

<http://linked.data.gov.au/def/borehole-status/not-producing-gas>
    skos:prefLabel "Not Producing CSG"@en ;
.

<http://linked.data.gov.au/def/borehole-status/shut-in>
    skos:prefLabel "Shut In"@en ;
.

<http://linked.data.gov.au/def/borehole-status/suspended>
    skos:prefLabel "Borehole Operations Suspended"@en ;
.

<http://linked.data.gov.au/def/borehole-status/workover>
    skos:prefLabel "Workover"@en ;
.
```

**Comment by rob-metalinkage** [comment]
Suggestion - put the API spec into a machine-readable form in a "proposals" or "incubation" or something subdirectory and let the issue express the essence succinctly to make it easier to parse.

Without a reference to an online example of a "scaling failure" its possibly hard to examine implications.

The obvious limitation of VocPrez is that large lists of vocabularies on the index page became useless and irritating - there needs to be a way of grouping families of vocabularies and lazy-loading on explicit expansion (without compromising search!)

For example, a real application schema may have many vocabularies defined as codelists -e.g. http://defs.opengis.net/vocprez/vocab/

check out "Pipeline-ML" - >100 codelists completely wrecks this view. 

Annotating Concept Schemes with some classification might work - but this would need to be configurable in the UI - probably supporting an ordered whitelist of classifications.  

Possibly a pre-load whitelist might be useful for the balance between first-look and performance scaling too.

AFAICT the average number of vocabularies for an observations based system would be about 30 - but this may be conservative if there is much heterogeneity in the observation sensors.

**Comment by edmondchuc** [comment]
Thanks Rob for the feedback. The new API is mainly to address loading very large vocabularies with thousands of concepts. Rather than loading all of the concepts of a vocabulary in one go, it will incrementally load just the top concepts in a paginated manner. More concepts will be fetched as the user performs more actions. Here's an example vocabulary, a [`thesaurus.nt`](https://github.com/BritishGeologicalSurvey/vocabularies/blob/main/vocabularies/thesaurus.nt) from the British Geological Survey with 6000+ concepts. To load this all in one go to render the vocabulary page with the concept hierarchy would take a long time and potentially run out of database memory.

> The obvious limitation of VocPrez is that large lists of vocabularies on the index page became useless and irritating - there needs to be a way of grouping families of vocabularies and lazy-loading on explicit expansion (without compromising search!)

I think what you're describing here is relevant but possibly a separate issue. I agree it would be nice to group the vocabularies using `dcterms:theme` or something similar to narrow down the list of vocabularies shown in the vocabulary listing page. However, what I'm trying to address here is the loading of concepts on a vocabulary page.

**Comment by rob-metalinkage** [comment]
OK fair enough - I'll add a new issue - the title "Add API to support loading vocabularies incrementally" is ambiguous - which reinforces my point about needing a succinct summary and the detail in supporting files :-)

**Comment by edmondchuc** [comment]
Hi Rob, yes I agree with you, looking back at the title and my opening description, it is ambiguous! I've hopefully fixed it up with the new title and summary description in the opening post.

**Comment by jamiefeiss** [comment]
Sounds like a good starting point. I agree that we're definitely going to run into issues for large & complex vocabularies. Separating out these endpoints & paginating concepts makes sense, and the UX in the frontend would be pretty seamless with smaller async calls when expanding to show narrower concepts.

I think this also highlights a more fundamental issue with the API in general - item endpoints should only return data that is relevant for that endpoint, which means returning less (if any) data about children. Same goes for listing endpoints, which at the moment return the same data for each item as each item endpoint separately. Improving on these points would lead to pretty significant performance improvements in general.

What do you guys think @nicholascar @recalcitrantsupplant ?

**Comment by recalcitrantsupplant** [comment]
> item endpoints should only return data that is relevant for that endpoint, which means returning less (if any) data about children. Same goes for listing endpoints, which at the moment return the same data for each item as each item endpoint separately. 

Can you link to an example of this - the listing queries/endpoints only return URIs + annotations for member items, and the object endpoints typically (profile dependent) return more information, so you shouldn't be seeing that unless the profiles were set to do so.

@edmondchuc new endpoints for narrower / top concepts sounds good - are the queries for these not slight modifications to the existing listing queries though?

Do you want to consider a /count endpoint as well? this was the other (in addition to ordering) triplestore performance bottleneck we've encountered in the past.

**Comment by edmondchuc** [comment]
> new endpoints for narrower / top concepts sounds good - are the queries for these not slight modifications to the existing listing queries though?

Possibly, but I think not using the listing queries here is fine. The queries are not going to change much as it's just loading concepts using predicates from SKOS. It also makes testing a lot easier too. For example, if a new use case comes up and requires changes to the listing queries, it will require changes to the existing tests for each subsystem that uses those listing queries as well. The new queries are here in the PR in [prez/services/vocprez.py](https://github.com/RDFLib/prez/pull/134/files#diff-ff595ef18a2834f6d982e4535218f8bc62f02389f1737e685c7083bf8a8470cb).

> Do you want to consider a /count endpoint as well? this was the other (in addition to ordering) triplestore performance bottleneck we've encountered in the past.

Each of the endpoints already provide counts back. Do you mind explaining a bit how you envisage a `/count` endpoint would work?
