### ISSUE TITLE
Function to dump Prez-generated prefixes

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/prez#136]
This function can be used to dump a set of generated prefixes by Prez as a way to bootstrap the Prez prefixes for a new dataset.

This function can be exposed through a web API at an endpoint like `/system/prefixes`.

**Comment by recalcitrantsupplant** [comment]
Functionality added in https://github.com/RDFLib/prez/pull/264 and coming in v4 PR

**Comment by recalcitrantsupplant** [comment]
Included in https://github.com/RDFLib/prez/pull/265 for v4.0

**Comment by recalcitrantsupplant** [comment]
#265 merged
