### ISSUE TITLE
The drop-down list profiles are not implemented yet (JSON/CSV)

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/prez#147]
Need to do some design and research in the best way to implement this. 

- How does the profiles define the properties to generate the result?
- What is the schema for the result? Identifier and label?
- Do we need a background job of some sort for very large objects? How do we handle large objects with 10s of thousands of values?

**Comment by recalcitrantsupplant** [comment]
JSON completed
CSV to do
Tests to add

**Comment by hjohns** [comment]
Future tasks:
1- remove logic from pydantic into standard routes or renderer
2- system links now have classes, where a profile/subsystem combo (filter) is not provided in the future all the rdf will be returned for an object. 
3- class/media type --> matching profiles with class/media type --> preferences --> profiles/media types in preference order
4- make sure our /object page is not broken
