### ISSUE TITLE
Review Proposed Prez Profiles

### ISSUE THREAD

**Issue by recalcitrantsupplant** [RDFLib/prez#172]
https://rdframe.sgraljii8d3km.ap-southeast-2.cs.amazonlightsail.com

**Comment by jamiefeiss** [comment]
- Add in top concepts endpoint
- Add in "exists" method to determine if grandchildren exists
- Keep counting separate in the backend
- Future enhancement - bring additional terms from the subquery into the construct

**Comment by recalcitrantsupplant** [comment]
add sh:rule to documentation, which allows adding triples to the CONSTRUCT clause

**Comment by hjohns** [comment]
Review has been done, documentation to be coordinated with Lawson.

**Comment by recalcitrantsupplant** [comment]
sh:rule not currently supported in order to avoid shacl sparql and make query generation more robust. Can bring back if required.
