### ISSUE TITLE
integrate RDFrame based profiles into Prez Backend

### ISSUE THREAD

**Issue by recalcitrantsupplant** [RDFLib/prez#173]

**Comment by recalcitrantsupplant** [comment]
MVP completed

**Comment by hjohns** [comment]
Implements new OGC records API endpoints.

**Comment by hjohns** [comment]
David to share link once the API is up.

**Comment by recalcitrantsupplant** [comment]
Updated to reflect extended OGC Records format:
https://prez-v4-single-endpoints.sgraljii8d3km.ap-southeast-2.cs.amazonlightsail.com/
/catalogs/{catalog_id}/collections/{collection_id}/items/{item_id}

**Comment by recalcitrantsupplant** [comment]
Integrated; PR open https://github.com/RDFLib/prez/pulls
