### ISSUE TITLE
Aquire all system labels from Semantic Background

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#213]
All the vocabs and ontologies in [context_ontologies](https://github.com/RDFLib/prez/tree/main/prez/reference_data/ context_ontologies) and all of the prefixes in [prefixes](https://github.com/RDFLib/prez/tree/main/prez/reference_data/prefixes) that are generic, i.e. useful beyond Prez, should come from https://github.com/Kurrawong/semantic-background. This way we can maintain one set of labels only.

**Comment by recalcitrantsupplant** [comment]
This has been done
