### ISSUE TITLE
Improve builtin labels

### ISSUE THREAD

**Issue by lalewis1** [RDFLib/prez#218]
- [x] Replace rdf in `prez/reference_data/context_ontologies` with the annotations from the sematic background repo.
- [x] rename context_ontologies to annotations.
- [x] make sure that prez still loads them into the annotations repo

**Comment by lalewis1** [comment]
In doing the above, I have discoverd that there are issues in the semantic background annotations. namely that there are multiple definitions for the same things. for example a label for dcterms:creator is given in both dcterms and pav.

prez returns all the labels and in this case a poor label is chosen. I'm sure other instances of this exist, so I need to go back to the semantic background and clean them up so that only definitions for terms from the current vocab are captured in the annotations, so as to not clash with the authority of the source ontology.

**Comment by lalewis1** [comment]
duplication of labels issue is now resolved.
However, I noticed now that a lot of the tests are failing because (the hard coded) expected responses for some requests (like in test_dd_profiles) are expecting the descriptions / labels that were given in the old context_ontologies/*.nq files.

probably not worth trying to resolve (as I based my branch off main.) might have to go back and create a new branch off one of the newer branches and put in the effort to patch the tests their.

**Comment by recalcitrantsupplant** [comment]
Yes it will be

**Comment by lalewis1** [comment]
Thanks,

implemented and all tests passing but not tested with prez-ui. just waiting for Jamie to help me get prez-ui set up locally so I can test that and then I will submit a PR.

**Comment by lalewis1** [comment]
Tested with prez ui v4 and all semback labels are displaying nicely.

**Comment by recalcitrantsupplant** [comment]
@lalewis1 can this be closed now?

**Comment by lalewis1** [comment]
yep.
