### ISSUE TITLE
URI - URL alignement

### ISSUE THREAD

**Issue by tendrie** [RDFLib/prez#232]
Hi all,

We are trying to find "rules" from our proxy/resolver to make the URL of ressources  in prez UI corresponding to the URI of the ressource itself. In prez API, it's ok.

Is it possible to perform that by rewriting rules?

1. for datasets: s/datasets/******
2. for catalogs: c/catalogs/*****

how the "******" part is generated? there is some namespace prefixes within and how it is generated.

Could you give us some idea to do so? It's really important for our UC that the URI and the URL remains the same.

Thank you

**Comment by recalcitrantsupplant** [comment]
The xxx parts of the links are CURIES. The namespace prefixes for the curies can either be generated on startup, or specified. The generation function is intended to be deterministic but it's not guaranteed. Specifying prefixes should make them deterministic. I would recommend specifying prefixes - this will also mean you can choose "nice" prefixes. You can specify prefixes by adding a turtle file to prez/reference data/prefixes, use the same format as the existing files in that location. If you need to identity the namespaces used in your data, there is a sparql query on the developer readme to assist with this.

**Comment by recalcitrantsupplant** [comment]
@tendrie did you have any success with the above?

**Comment by tendrie** [comment]
@recalcitrantsupplant 
Thank you for your answer, we have tried to specify prefixes as you said, and it works nicely.
Thank you
