### ISSUE TITLE
Force Cache Reload endpoint

### ISSUE THREAD

**Issue by lalewis1** [RDFLib/prez#237]
It would be good to have an endpoint to force Prez to reload the cache.

Notably, this is an issue when adding new labels and changing URIs.

**Comment by recalcitrantsupplant** [comment]
This should be what `/purge-tbox-cache` does - could you confirm it works with the data you're using

**Comment by lalewis1** [comment]
oh awesome. thanks. sorry I thought you said the other day that this didnt exist. but yeah that works just like what I needed.

**Comment by recalcitrantsupplant** [comment]
I think you were asking about prefix resetting; there's a separate namespace/prefix manager which there currently is no endpoints to manage. If you add more data with new namespaces, prez should automatically generate new prefixes for these.

**Comment by lalewis1** [comment]
ah thats right.
