### ISSUE TITLE
Establish new URL response workflow

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#25]
First pass process:

![image](https://user-images.githubusercontent.com/7321872/188439852-d1b3aac2-c052-46d9-b448-be9c2efce53f.png)

**Comment by recalcitrantsupplant** [comment]
The most common flow (retrieve object by identifier(s)) would use a default profile for an endpoint, or get a profile from a request. In this case do we need to know/care about the class(es)? Needed for alt profiles listing only?

**Comment by recalcitrantsupplant** [comment]
Re. my above comment - yes the classes are always relevant, and class -> profile data ends up cached so no concern re. performance.

Above response workflow is now implemented.
