### ISSUE TITLE
Create profiles standard Classes

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#28]
Create the SPARQL queries to get minimal valid instance data for the following classes per Profile (Prez defaults):

* Class
    * Everything / Alternates
* ConceptScheme
    * SKOS, VocPub
* Collection
    * SKOS, VocPub
* Concept
    * SKOS, VocPub
* Dataset
    * PROV, DCAT, SpacePrez
* FeatureCollection
    * PROV, GeoSPARQL, SpacePrez
* Feature
    * PROV, GeoSPARQL, SpacePrez
* Catalog
    * PROV, DCAT, CatPrez
* Resource
    * PROV, DCAT, CatPrez
* Distribution?

**Comment by recalcitrantsupplant** [comment]
Complete except GeoSPARQL and https://github.com/RDFLib/prez/issues/13 PROV https://github.com/RDFLib/prez/issues/89 - see these issues
