### ISSUE TITLE
Catalog Counts are incorrect

### ISSUE THREAD

**Issue by lalewis1** [RDFLib/prez#283]
Noted that sometimes the prez:count value for a listing of /catalogs does not always match the number of catalogs shown.

![image](https://github.com/user-attachments/assets/fa4e391e-2c1a-44b8-b935-b7a2f98e2a29)

pending further investigation

**Comment by recalcitrantsupplant** [comment]
Is this resolved by #3 in https://github.com/RDFLib/prez/pull/281

**Comment by lalewis1** [comment]
ah, probably. will do that review.

**Comment by lalewis1** [comment]
resolved  in #281
