### ISSUE TITLE
Define the Prez and sub-Prez API endpoints

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#29]
Define all endpoints for:

* Prez
    * home
    * search
    * pages
    * sub-Prez homepage
    * about
* sub-Prezes - CatPrez, SpacePrez, VocPrez
    * each class
    * individual Conformance pages
    * special search

**Comment by nicholascar** [comment]
### Prez

**Endpoint** | **Content**
--- | ---
/ | System home. Gives basic Prez info, lists all enabled sub-Prez
/sparql | Single SPARQL endpoint for all Prezs
/search | Unified search page
/docs | API Docs - autogen
/profiles | Listing of all the Profiles known to the system, and the classes the constrain
/x | /c, /s, v: all enabled Prez' homepages
/object | Gets a single object in the DB by IRI, `/object?iri=...`

### SpacePrez

**Endpoint** | **Content**
--- | ---
/s | SpacePrez system home == spatial datasets catalogue. Also info about SP endpoints & structure
/s/datasets | SpacePrez catalog - dataset listing
/s/datasets/{DATASET-ID} | SpacePrez view of a Dataset
/s/datasets/{DATASET-ID}/collections | Feature Collections within a spatial Dataset
/s/datasets/{DATASET-ID}/collections/{FC-ID} | Metadata about an FC
/s/datasets/{DATASET-ID}/collections/{FC-ID}/(items\|features) | FC's Features list
/s/datasets/{DATASET-ID}/collections/{FC-ID}/(items\|features)/{FEATURE-ID} | A Feature

A request for `/object?iri=x` where `x` appears in multiple Datasets/FCs will result in a listing of the individual Dataset/FC/Item system URLs to access that Feature by.

### CatPrez

**Endpoint** | **Content**
--- | ---
/c | CatPrez system home == datasets catalogue. Also info about CP endpoints & structure
/c/catalogs | Catalog of catalogues. Will List the SP & VP catalogues, if enabled
/c/catalogs/{CAT-ID} | A Catalog
/c/catalogs/{CAT-ID}/resources | Resources within a Catalog
/c/catalogs/{CAT-ID}/resources/{RESOURCE-ID} | A Resource within a Catalog

A request for `/object?iri=x` where `x` appears in multiple Catalogues will result in a listing of the individual Catalog/Resource system URLs to access that Resource by.


### VocPrez

**Endpoint** | **Content**
--- | ---
/v | VocPrez system home == vocabularies catalogue. Also info about VP endpoints & structure
/v/vocabs | Catalog of vocabularies
/v/vocabs/{VOC-ID} | A Vocabulary
/v/collections | List of Collections
/v/collections/{COLLECTION-ID} | A Collection
/v/vocabs/{VOC-ID}/{CONCEPT-ID} | A Concept within a Vocabulary

A request for `/object?iri=x` where `x` is a Concept that appears in multiple Vocabularies will result in a listing of the individual Vocabulary/Concept system URLs to access that Concept by.

**Comment by recalcitrantsupplant** [comment]
This is defined in the main readme
