### ISSUE TITLE
Vue.js front end

### ISSUE THREAD

**Issue by jamiefeiss** [RDFLib/prez#30]
Having a JavaScript front end like [Vue.js](https://vuejs.org/) would give Prez a much nicer look and be easier to develop and maintain. It would also reduce the work Prez needs to do data-wise to present a HTML view. The front end could receive RDF content from Prez using [rdflib.js](https://www.npmjs.com/package/rdflib) from some internal "front end"/HTML profile.

The main concern with a JS front end is theming & customising HTML content. Things like colours, logos, fonts & custom CSS can be done using a system config file or object that Vue reads. For HTML content, since the main parts of a page that are customised are the header and footer, we could expose those elements specifically to insert static content. These elements would live outside of Vue:

```html
<header>...</header>
<div id="app"></div> <!-- Vue app -->
<footer>...</footer>
```

The API & front end can either be deployed separately or as a bundle of two containers (e.g. docker compose & kubernetes can do this).

If we need to return HTML content that's machine readable, we could look into [server-side rendering](https://vuejs.org/guide/scaling-up/ssr.html) (SSR) for Vue. This would also give performance improvements for the front end.

**Comment by Ndace-hash** [comment]
Hello I am a frontend Developer working with Vue.js and I would like to contribute to your project, Can I get Assigned a task?

**Comment by recalcitrantsupplant** [comment]
Hi Zaccheaus, apologies for the slow reply, head over to https://github.com/RDFLib/prez-ui and see if one of one of the widget issues looks like something you'd be interested in. This repo (https://github.com/RDFLib/prez/) is now for the backend API which does not use Vue.js. We still need to put together examples of how to run the front and backend together.
