### ISSUE TITLE
A concept with large number of narrowers results in a loading timeout

### ISSUE THREAD

**Issue by luoenzhen** [RDFLib/prez#303]
Prez version: 3.8.4
(also tested on Prez 3.8.14 locally).
We have a concept (`CF standard name` http://linked.data.gov.au/def/tern-cv/8e7a785a-8c57-4415-855f-cb6d35ad58bb) with over 5000 skos:narrower properties. When browsing that concept, prez constructs a query over 2MB to retrieve narrower's label and uri.
[cf_standard_name_query.txt](https://github.com/user-attachments/files/17709141/cf_standard_name_query.txt)
The construction of that large query will take up to 3 to 4 minutes.
Is it possible to optimise the construction and/or add paging to the query to allow fast loading without blocking the UI?

**Comment by recalcitrantsupplant** [comment]
which version of prez are you using? the current one does paginate the concept hierarchy queries (top concepts, narrowers), which should in turn prevent trying to get labels for 5000 concepts.

**Comment by luoenzhen** [comment]
I updated the comment.

**Comment by luoenzhen** [comment]
SPARQL_ENDPOINT="https://graphdb.tern.org.au/repositories/tern_vocabs_core"

**Comment by recalcitrantsupplant** [comment]
You can modify the vocpub profile to exclude skos:narrower:

`prez/reference_data/profiles/vocprez_default_profiles.ttl`

```
    altr-ext:hasNodeShape [
        a sh:NodeShape ;
        sh:targetClass skos:Concept ;
        altr-ext:focusToParent skos:inScheme ;
        **altr-ext:exclude skos:narrower ;**
    ] ;
```

Because the generated query can only FILTER predicates the intermediate result containing may still be slow.
```
            <http://linked.data.gov.au/def/tern-cv/02b5e72b-ec65-4ed8-aa6a-e55e448680c2> ?p ?o1 . 
             FILTER(?p NOT IN (<http://www.w3.org/2004/02/skos/core#narrower>))          
```
You could either switch to specifying predicates to include (using sh:path), or modify your data to use skos:broader rather than skos:narrower.

**Comment by luoenzhen** [comment]
I tried with excluding the skos:narrower and the loading time is same. Also we need the skos:narrower for the concept, so we can't exclude it.

**Comment by recalcitrantsupplant** [comment]
Your best option would be to include the other predicates you need via sh:path, except skos:narrower, and then hit the 
`/v/vocab/{concept_scheme_curie}/{concept_curie}/narrowers` endpoint, which is paginated, and use the RDF merge of that.

**Comment by luoenzhen** [comment]
That `/v/vocab/{concept_scheme_curie}/{concept_curie}/narrowers?page=1&per_page=50` works great. Thanks.

**Comment by luoenzhen** [comment]
I still haven't figured out how to customise the predicates via sh:path.

**Comment by recalcitrantsupplant** [comment]
line 108 in the file I linked to above, you need something like this. You'll need to identify all the possible predicates that the skos:Concepts could have, then add them like this:

```
    altr-ext:hasNodeShape [
        a sh:NodeShape ;
        sh:targetClass skos:Concept ;
        altr-ext:focusToParent skos:inScheme ;
        sh:path your:pred1 , your:pred2 , your:pred3 ;
    ] ;
```

**Comment by luoenzhen** [comment]
Thanks again. Does that mean we need to maintain our own prez with that change?

**Comment by recalcitrantsupplant** [comment]
No you can add a custom profile to the triplestore and prez will pick it up on startup. i.e. a copy of the modified ttl file. You will probably need to call it something other than vocpub though, and get the UI to request this modified profile, as I don't think prez will merge the two profiles nicely due to blank nodes.

If you're able to, I would suggest moving to prez v4.

**Comment by luoenzhen** [comment]
Prez V4's endpoints are bit different from Prez V3.

**Comment by luoenzhen** [comment]
Do we have a working UI for prez v4 please?

**Comment by recalcitrantsupplant** [comment]
In prez v4 you can specify your own class hierarchy and routing. e.g. you can specify the routes to be /vocabs/{vocabId}/concepts/{conceptId}. The documentation is here: https://github.com/RDFLib/prez/blob/main/README-Custom-Endpoints.md
What you can't yet have is two sets of routes i.e. /vocabs/... and /collections/... . The plan is to add this functionality.
You can have one route that serves multiple class hierarchies though. So you can have /things which lists both Concept Schemes and Collections.

Yes there is a working UI. @hjohns can point you in the right direction in terms of documentation/setup.

I'll close this as an issue but if you wish please open a discussion here: https://github.com/RDFLib/prez/discussions

**Comment by hjohns** [comment]
Hi @luoenzhen. We are still in the process of documenting and finalising the UI app for v4. However, in the meantime you can point our v4 demo UI instance to any Prez API endpoint to test how it renders.

Steps:
1. Go to the endpoint test page --> https://demo.dev.kurrawong.ai/endpoint-tester
2. Enter your Prez API endpoint
3. Press "Set" (this should show that you are using a custom endpoint now)
4. Go to catalogs --> https://demo.dev.kurrawong.ai/catalogs
5. You should see catalogs from your Prez API instance

If you use a http not https Prez API endpoint you may hit a browser security issue. If that's a problem, maybe we can make a http version accessible as well.

Let me know how it goes.

**Comment by luoenzhen** [comment]
Hi @hjohns , I tried with v3 endpoint (https://linkeddata-test.tern.org.au/api/tern-cv) 'cause right now we don't have v4 endpoint and it doesn't work with the v4 demo UI.

**Comment by luoenzhen** [comment]
> Your best option would be to include the other predicates you need via sh:path, except skos:narrower, and then hit the `/v/vocab/{concept_scheme_curie}/{concept_curie}/narrowers` endpoint, which is paginated, and use the RDF merge of that.

The response is text/turtle, can we return the response in Json format pls?

**Comment by luoenzhen** [comment]
> No you can add a custom profile to the triplestore and prez will pick it up on startup. i.e. a copy of the modified ttl file. You will probably need to call it something other than vocpub though, and get the UI to request this modified profile, as I don't think prez will merge the two profiles nicely due to blank nodes.

Hi David, I tried this method and rename the profile as http://www.w3.org/ns/dx/prof/Profile (if I understand that readme-dev file correctly) and imported to my triplestore. However, it still doesn't work as expected. Anything I missed?

**Comment by recalcitrantsupplant** [comment]
Are you able to post the entire profile that you created in the discussion - I closed this issue as I don't think there's an issue/feature request etc. here

**Comment by luoenzhen** [comment]
> Are you able to post the entire profile that you created in the discussion - I closed this issue as I don't think there's an issue/feature request etc. here

I've added the entire profile.

**Comment by recalcitrantsupplant** [comment]
I've closed this issue could you please add it to one of the discussions
