### ISSUE TITLE
The version value should be updated to reflect the current prez version.

### ISSUE THREAD

**Issue by luoenzhen** [RDFLib/prez#304]
After the prez installation, it still shows `Installing the current project: prez (0.1.0.dev0)`

**Comment by recalcitrantsupplant** [comment]
This will likely be addressed in https://github.com/RDFLib/prez/issues/270

Could you confirm this is just an issue when running locally?

You can set the prez_version setting (or PREZ_VERSION env var) if you're deploying it and want the correct version to show. Ideally this would be automatic though as you say.

**Comment by luoenzhen** [comment]
Yes, it occurs only locally. I will close it.
