### ISSUE TITLE
Provide configurable control over nested and linked object shapes

### ISSUE THREAD

**Issue by rob-metalinkage** [RDFLib/prez#31]
When an object property references another object, the level of detail required and sensible to show is somewhat variable - for example a value with units object probably needs to be completely rendered, but a back link to a container should not result in rendering all the contents of the container.

Configuring a default object rendering for classes would make sense and be quite reusable, and have the benefit of consistency.  Smart widgets - with minimal and expanded view sets of properties - would help.   

Configuration to override default for subject-class + property combinations as well.

**Comment by recalcitrantsupplant** [comment]
This is catered to via the profiles - if a specific set of RDF is provided as an example with the desired profiled view we can demonstrate this

**Comment by rob-metalinkage** [comment]
To close this please provide a link to an example showing it working (or source data and a screenshot at least)
