### ISSUE TITLE
Malformed URIs break serialisation and UI rendering

### ISSUE THREAD

**Issue by cfollenf** [RDFLib/prez#315]
Dear all,

We are facing errors when Prez attempts rendering resources with malformed URIs. Specifically, our data happens to have triples with URIs containing URL-unencoded quotes for JSON content, such as:

`<http://www.example.org/board?t=example&qparams="%7BlastOnly%3Aon%2CallNotGdacs%3A1%2Cnetworks%3A1%2Cstatus%3A6%7D"&modules=%5B%7Bid%3A01%7D%5D>`

While the backend Fuseki and its UI web app are able to handle these, Prez (and subsequently Prez-UI) breaks with an ASGI exception and returns a 500. We understand this issue is data-specific, still, would it be possible for Prez to handle them as transparently as Fuseki does?

**Comment by recalcitrantsupplant** [comment]
Hi Corentin, will try take a look later today, I guess it depends how/where it's breaking. I see RDFLib at least can parse it.

**Comment by cfollenf** [comment]
Perhaps I can provide further details:

Our erroneous data basically has the underlying scheme:
```
:myResource a dcat:Dataset ; dcat:endpointURL <myMalformedURL"withquotes">
```
When calling a Prez-UI page supposed to display it, or its underlying Prez endpoint, the Fuseki container receives a query asking for `SELECT ?class { <myMalformedURL"withquotes"> a ?class }` and actually returns a WARN, which seems Prez isn't able to ignore or bypass:
![image](https://github.com/user-attachments/assets/1fa71f85-dcdf-4621-8947-f210bae83cb7)
I was firstly mistaken when saying Fuseki handles such malformed URIs, as even though it seems to (as well as its webapp) it could be responsible for that ASGI exception.

**Comment by recalcitrantsupplant** [comment]
RDFLib's serializers reject the malformed URI. The only endpoint which entirely avoids them is the SPARQL endpoint with non-annotated mediatypes: `http://localhost:8000/sparql?query=select%20*%20{?s%20?p%20?o}`
In all other cases you'll get something like:
```
  File "/home/david/PycharmProjects/prez/.venv/lib/python3.13/site-packages/sparql_grammar_pydantic/grammar.py", line 112, in render
    yield self.value.n3()
          ~~~~~~~~~~~~~^^
  File "/home/david/PycharmProjects/prez/.venv/lib/python3.13/site-packages/rdflib/term.py", line 325, in n3
    raise Exception(
        f'"{self}" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?'
    )
Exception: "http://server/unset-base/myMalformedURL"withquotes"" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?
```
In addition to the above:
1. I couldn't add a test as the test client uses PyOxigraph, which rejects the URI.
2. With a little difficulty I could get the URI into Fuseki (INSERT via the UI did not work for me), however it still complains about the URI, although it did respond to the SPARQL query with the malformed URI.

I think you're going to have issues with one library or another sooner or later - the best option would be to fix the URIs. Closing as I don't believe this would be worth the effort to support sorry.
