### ISSUE TITLE
Inverse path properties

### ISSUE THREAD

**Issue by rob-metalinkage** [RDFLib/prez#33]
Provide a configurable means to specify inverse paths to related objects when rendering.

**Comment by nicholascar** [comment]
Can you give an example in RDF? 

Do you mean something like this: if I have a Feature in a Feature Collection, but only FC -> feature specified with `rdfs:member` in the data, I could specify an inverse like `ex:memberOf`. But how would I know to build that inverse property out?

If you just make up an inverse now like `ex:memberOf` and add it to data, it will show up in object rendering as a property. 

We could implement a set of common inverses, like the above for GeoSPARQL.

**Comment by rob-metalinkage** [comment]
Well a classic example for be to find observations on a featureOfInterest using the SOSA model.  Not a fan of calculating every possible inverse - as many models do not define suitable inverse properties.

**Comment by rob-metalinkage** [comment]
would be better to have configurable rather than "common" inverses in the design.  And probably active vs lazy options for navigation and rendering.

**Comment by recalcitrantsupplant** [comment]
This could be done by extending the profiles to allow "sh:construct" - prez would then append this SPARQL CONSTRUCT query to the default SPARQL query for an object.

For example if the standard object query is along the lines of:

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {?s ?p ?o .
  ?o ?p2 ?o2 .
  ?o2 ?p3 ?o3 } 
WHERE {
  BIND(<feature_uri> AS ?s)
  ?s !rdfs:member ?o ;
      ?p ?o
  OPTIONAL {
    FILTER(ISBLANK(?o))
    ?o ?p2 ?o2 ;
       OPTIONAL {
      FILTER(ISBLANK(?o2))
      ?o2 ?p3 ?o3 ;
          }
  }
}
```
Additions to the query, for example for inverse paths, of the form
```
CONSTRUCT {?s ?p ?o}
WHERE {
?s ?p ?o ;
     sosa:hasFeatureOfInterest <feature_uri>}
```
Can be merged (in Prez, using Python) with UNION, e.g.:
```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {?s ?p ?o .
  ?o ?p2 ?o2 .
  ?o2 ?p3 ?o3 } 
WHERE 
{
 {
  BIND(<feature_uri> AS ?s)
  ?s !rdfs:member ?o ;
      ?p ?o
  OPTIONAL {
    FILTER(ISBLANK(?o))
    ?o ?p2 ?o2 ;
       OPTIONAL {
      FILTER(ISBLANK(?o2))
      ?o2 ?p3 ?o3 ;
          }
   }
 }
UNION
 {
  BIND(<feature_uri> AS ?s)
  ?s ?p ?o ;
       sosa:hasFeatureOfInterest <feature_uri>
 }
}

To be clear the sh:construct would be added to the profiles such as this example: https://github.com/surroundaustralia/ga-spaceprez-profile/blob/main/ga-profile.ttl

Not sure where exactly in the profile the `sh:construct` would go, perhaps under a node shape. The SHACL spec might give guidance here

**Comment by rob-metalinkage** [comment]
thats my thinking too - property paths with inverse are declarative - turning these into constructs ought to be implementation.

This is important because we can query declarative paths - e.g. to find all outputs that include a particular path content -whereas looking inside SPARQL is nastier.  Also, decomposing SPARQL to take advantage of cached object details would be hard.

**Comment by recalcitrantsupplant** [comment]
OK so the profile would have something like "sh:inversePath", which could get translated in to a CONSTRUCT by Prez?

**Comment by recalcitrantsupplant** [comment]
Implemented, see https://github.com/RDFLib/prez/blob/546e1f2184506a80f53741831b36afe4e22da28b/prez/services/sparql_new.py#L19 and https://github.com/RDFLib/prez/blob/546e1f2184506a80f53741831b36afe4e22da28b/prez/services/sparql_new.py#L360
