### ISSUE TITLE
Thorough testing structure

### ISSUE THREAD

**Issue by jamiefeiss** [RDFLib/prez#35]
We will need to create a solid structure for tests, and create tests for every feature of Prez. These tests would include:

- Unit tests
- Integration tests
- API tests
  - Content negotiation by profile
  - Standard conformance testing (e.g. OGC API)
- Front end tests (for Vue.js) using Vitest
- Possibly UX testing using Selenium (this could include testing across different browsers)

**Comment by recalcitrantsupplant** [comment]
agree on the need for more testing - need to break this in to specific tasks so they can be tracked/managed i.e. probably the items you've listed
