### ISSUE TITLE
Documentation for users & developers

### ISSUE THREAD

**Issue by jamiefeiss** [RDFLib/prez#36]
Users will need documentation for more info on Prez & how to use it. This could involve GitHub pages with Jekyll.

Developers would find dev documentation useful as well, and should be documenting their code throughout development. Using [Sphinx](https://www.sphinx-doc.org/en/master/) for automatic Python documentation generation could be one option to go with.

The Vue.js front end (if implemented) could also have some development documentation. [Vuepress](https://vuepress.vuejs.org/) is one option (not auto-generated like Sphinx, it's more like Jekyll).

We could also use a single tool for all our documentation for simplicity.

**Comment by recalcitrantsupplant** [comment]
in progress documentation please create another issue for FE if required https://github.com/RDFLib/prez/blob/sparql_refactor/README-Dev.md
