### ISSUE TITLE
Consider GHCR instead of Dockerhub

### ISSUE THREAD

**Issue by recalcitrantsupplant** [RDFLib/prez#39]
I would choose it if only to reduce the number of technologies used.
No practical difference in how people pull the images.

A comparison here https://dev.to/github/github-container-registry-better-than-docker-hub-1o9k

**Comment by nicholascar** [comment]
We have asked the maintainers of RDFLib for a plan for the use of GHCR for Prez alongside GHCR for the mail RDFLib. They (2/5 maintainers) are keen to write GitHub actions  to produce an RDFLib image which we, Prez maintainers, can then copy. ETA on this is end of this week (17th Sept) so we should have a Prez image in GHCR next week.
