### ISSUE TITLE
Allow SPARQL endpoint do be selected in YASGUI

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#4]
Ideally from a predefined list i.e. those SPARQL endpoints which the API is set up to query

NB I think the existing SPARQL endpoint selector can be enabled in index.css by commenting out (or editing) the following:

```
#yasgui .autocompleteWrapper {
  display: none !important;
}
```

For cases where more than one Prez type is running e.g. spaceprez + vocprez

**Comment by recalcitrantsupplant** [comment]
implemented in FE.
BE unions responses from multiple endpoints.
