### ISSUE TITLE
Demonstrate Framed JSON-LD

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#44]
Demonstrate Prez service Framed JSON-LD. The first such content will be for:

* Agents in the IDN Agents Catalogue
* FAIR & CARE scores in the IDN Dataset Catalogue
* Standards relationships in the OGC Naming Authority Prez instance

Implementation Questions:

* Is it necessary to specify the Frames used per class of object or can generic rules for all objects classes be created?
* Does Framed JSON-LD need a different Media Type form JSON-LD?

@jamiefeiss @rob-metalinkage @avillar

**Comment by recalcitrantsupplant** [comment]
Have looked at using JSON-LD,
To use in BE would require writing a JSON-LD context -> SPARQL mapping the way we currently have for SHACL -> SPARQL.
This could work as an alternative to using the SHACL profiles.
Another option would be to do the JSON-LD profiles on the frontend using a JS library.

**Comment by rob-metalinkage** [comment]
Having looked into this I've given up on a decent framing solution driven by a top-down model in the short term - and am working on the OGC building blocks approach - json schema snippets bound to JSON-LD contexts.  You can see the spike solution here https://github.com/avillar/bblock-template (we are moving to an official OGC repo once we have completed more testing and documentation review) - or this one in development  https://github.com/opengeospatial/ogcapi-sosa

Note this provide granular control over re-usable patterns, and avoids the potential for complex framing specifications to re-invent the wheel each time.

**Comment by recalcitrantsupplant** [comment]
There's not current plan to integrate framing.
Having attempted this a few times the main issue I see is it would be difficult to use framing to replace SHACL for describing the CBD to retrieve - I think the intended use is a complete graph or document is the input and the framing acts on that.
