### ISSUE TITLE
Demo data extraction query params for GeoSPARQL Address, Feature & FeatureCollection

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#45]
We want Prez to be able to extract the data it needs for an object based on query parameters given to it in a profile implementation.

For example, within SpacePrez, the data Prez gets for a `Feature` should be specified by profiles such as GeoSPARQL since they affect the `Feature` class.

In this task, the specification of GeoSPARQL's `Feature` class, `FeatureCollection` class (since its a container-type of class) and the [Address Model](https://nicholascar.com/anz-nat-addr-model-candidate/model.html)'s `Address` class, since it's a specialisation of `Feature` should be specified, so that we can work out how specification occurs.

So far, the ideas we have are that profile implementations will need to indicate:

* whether or not the query is to be _open_ or _closed_
    * _open_: include such-and-such properties and anything else
    * _closed_: include only such-and-such properties, nothing else
* if lists of included/excluded properties should be given
    * this may collide with open/closed
* property ordering for HTML display
    * `sh:order`...
* what properties might lead to large numbers of things
    * e.g. `rdfs:member`
* inverse properties to look for
* a primary label property
* how many edges to follow away from this object
    * only for BNs?
    * property chains
    * default probably only 2, to cater for directly-linked Blank Nodes

**Comment by recalcitrantsupplant** [comment]
>     * whether or not the query is to be _open_ or _closed_
>       
>       * _open_: include such-and-such properties and anything else
>       * _closed_: include only such-and-such properties, nothing else
> 
>     * if lists of included/excluded properties should be given
>       
>       * this may collide with open/closed
> 
I propose open is defined as all properties EXCEPT those explicitly excluded. This is currently implemented with dash:hidden - see GA SpacePrez example. https://github.com/surroundaustralia/ga-spaceprez-profile/blob/main/ga-profile.ttl

>     * property ordering for HTML display
>       
>       * `sh:order`...
> 
+ grouping via. sh:group; though the groups haven't yet been used ..
>     * what properties might lead to large numbers of things
>       
>       * e.g. `rdfs:member`
Yes we either handle these simply as excluded properties i.e. pretend a FeatureCollection doesn't have members (!)
Or we implement special handling which would need a LIMIT and perhaps separate SPARQL CONSTRUCT to bring back a limited number of members
> 
>     * inverse properties to look for
I think sh:inversePath and sh:sequencePath for more complicated paths cover this. The construction of a SPARQL query from this should be fairly trivial.
> 
>     * a primary label property
Flagging that prez will need to change from being hardcoded to expect rdfs:label.
Not sure on property to use for this.
> 
>     * how many edges to follow away from this object
>       
>       * only for BNs?
yes, as MVP only for BNs
>       * property chains
no, do whatever is specified in the property chain using sh:sequencePath above
>       * default probably only 2, to cater for directly-linked Blank Nodes
Again not sure on property - probably need to create something

**Comment by recalcitrantsupplant** [comment]
All implemented in profiles except for sh:order: I propose this is handled in the frontend, else an RDF List would need to be created in the SPARQL results. Don't believe there is an elegant way to do this. Frontend has the profiles graph with predicates and their sh:order - I suggest it is easier to implement here.
