### ISSUE TITLE
System Profiles

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#52]
For SpacePrez, {SUBSYSTEM} --> /s

Endpoint | Default Profile | Default MT
--- | --- | ---
{SUBSYSTEM} | ? (Prez) | Annotated RDF
{SUBSYSTEM}/ | ? (Prez) | Annotated RDF
{SUBSYSTEM}/datasets | DCAT | Annotated RDF
{SUBSYSTEM}/datasets/{datasetId} --> ROOT | DCAT | Annotated RDF
{SUBSYSTEM}/api | OGC API | JSON
{SUBSYSTEM}/conformance | OGC API | JSON
{SUBSYSTEM}/{ROOT}/ | OGC API | JSON
{SUBSYSTEM}/{ROOT}/api | OGC API | JSON
{SUBSYSTEM}/{ROOT}/conformance | OGC API | JSON
{SUBSYSTEM}/{ROOT}/collections | OGC API | JSON
{SUBSYSTEM}/{ROOT}/collections/{collectionId} | OGC API | (Geo)JSON
{SUBSYSTEM}/{ROOT}/collections/{collectionId}/items | OGC API | (Geo)JSON
{SUBSYSTEM}/{ROOT}/collections/{collectionId}/items/{featureId} | OGC API | (Geo)JSON

**Comment by recalcitrantsupplant** [comment]
Updated API structure is in https://github.com/RDFLib/prez/pull/265 and main readme
