### ISSUE TITLE
Initial HTTP HEAD request rejected by some SPARQL endpoints

### ISSUE THREAD

**Issue by avillar** [RDFLib/prez#54]
Prez fails on startup when Fuseki (405) or RDF4J (400) are used due to the initial HTTP HEAD request that it sends to check whether the SPARQL endpoint is up.

Could a simple SPARQL query (e.g. `ASK { ?s ?p ?o }`) be used instead?

**Comment by recalcitrantsupplant** [comment]
Yes, I've updated this in the new version to an ask query. I'm working off the branch "sparql_refactor". Should have an updated version in the next 24 hours. Which version of Fuseki/how are you running it out of interest? We haven't had issues with Fuseki

**Comment by avillar** [comment]
I was running it against an old-ish 3.14.0. Maybe that was it. Thanks!
