### ISSUE TITLE
Ensure prefix for https://prez.dev/ namespace applied to all graphs

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#56]
Every time an RDFLib Graph() is created, it should use `Graph(bind_namespaces="rdflib")` and this is mostly done, but other, non-standard, namespaces like this one need to be added with `g.bind(...)`

**Comment by recalcitrantsupplant** [comment]
https://prez.dev/ used throughout + Graph(bind_namespaces="rdflib") 
"cdterms" typo will be resolved in future RDFLib release
