### ISSUE TITLE
Confirm the annotated RDF format

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#58]
When we return annotated/labelled RDF, we need to indicate this, something like a media type of `text/labels+turtle` or `application/labels+ld+json` etc. Need to ensure these are legal and would be understood as plain RDF (i.e. `text/turtle`, `application/ld+json`) if a system didn't know about "labels+".

**Comment by recalcitrantsupplant** [comment]
now using `text/anot+turtle`. Can reopen another issue if we want to add `application/anot+ntriples` etc.
