### ISSUE TITLE
Implement GeoJSON properties

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#6]
The GeoJSON view of a Feature, e.g. https://asgs.linked.fsdf.org.au/dataset/asgsed3/collections/SA1/items/10102100710?_profile=oai&_mediatype=application/geo+json, should list all the known properties for that Feature as GeoJSON _properties_.

Property keys can be pseudo JSON-LD, e.g, `sdo:name` with an `sdo: "https://schema.org/"` somewhere

**Comment by recalcitrantsupplant** [comment]
Issue is now to reimplement geojson
See requirements here:
https://docs.ogc.org/DRAFTS/20-004.html#core-queryables-record-table

**Comment by recalcitrantsupplant** [comment]
implemented using queryables + rdf2geojson package in prez v4
