### ISSUE TITLE
CQL Endpoints need to be turned on with SpacePRez enabled only

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#61]
I see 

![image](https://user-images.githubusercontent.com/7321872/207726159-7aba1bd9-f359-4899-97b5-628092593329.png)

when I only have VocPrez, so this is confusing and doesn't work. Need to turn it off unless SpacePrez is enabled.

**Comment by hjohns** [comment]
David to confirm with Nick.

**Comment by recalcitrantsupplant** [comment]
CQL is generally available on any listing endpoint - the current design doesn't distinguish / split out the functionality. It will be harmlessly ignored if no filter parameter is provided, or the CQL get/post endpoint is not used.

**Comment by recalcitrantsupplant** [comment]
closing
