### ISSUE TITLE
/search is missing

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#63]
I see it, https://github.com/RDFLib/prez/blob/sparql_refactor/prez/app.py#L184, but it's commented out!

We should have _at least_ a `/search` endpoint per Prez subsystem, powered up as previous prez' e.g. `/search?q=blah` for the standards VocPrez search. 

SpacePrez search could just be an endpoint alias for `/cql`

CatPrez search could be a weighted search, like VocPrez search, but for `dcat:Resource` title & description only for now (see https://github.com/surroundaustralia/vocprez-fedsearch/blob/master/fedsearch.py#L57)

Defer a whole-of-prez search (to Issue #64) for now but we should turn text indexing on for labels & descriptions for anything that has them (Concepts, Features, Resources) and then enable basic search on those fields.

**Comment by edmondchuc** [comment]
Adding this for future reference - CQL spec: https://portal.ogc.org/files/96288

**Comment by recalcitrantsupplant** [comment]
see: https://github.com/RDFLib/prez/discussions
