### ISSUE TITLE
Chrome can't download CSV results

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#66]
Clicking on a CSV media type link in VocPrez in Croome (or Edge) does not result in a CSV data display or file download.

Works fine in Firefox.

Works if the link is copies and re-pasted into Chrome address bar.

Suspect certain disposition headers need to be set.

e.g. http://gssa-prez-linux-web-app.azurewebsites.net/vocab/MD_MaintenanceFrequencyCode?_profile=dd&_mediatype=text/csv

**Comment by recalcitrantsupplant** [comment]
Couldn't reproduce issue on my version of chrome. Content disposition header added and pushed to SRA repo. Can see headers in SRA web app now.
https://gssa-prez-code-linux-web-app.azurewebsites.net
