### ISSUE TITLE
VocPrez filtering and searching not working

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#7]
### Filtering 

Standalone VocPrez had filtering of the vocabs list, e.g. https://vocabs.gsq.digital/vocabulary/?filter=borehole but Prez VP doesn't, e.g. https://linked.fsdf.org.au/vocab or http://gswa.kurrawong.net/

Standalone VP had working search, e.g. https://vocabs.gsq.digital/search?search=coal&from=all. Prez VP, stand-alone, search doesn't work e.g. http://gswa.kurrawong.net/search?search=geologic&endpoints=self nor does integrated Prez search, e.g. https://linked.fsdf.org.au/search?search=elevation&endpoints=self

**Comment by recalcitrantsupplant** [comment]
search needs to be made generic to accept arbitrary terms that have been added to template SPARQL search functions. See prez/routers/search.py

**Comment by recalcitrantsupplant** [comment]
see https://data.idnau.org/ 
https://github.com/RDFLib/prez/issues/90
