### ISSUE TITLE
Prez SPARQL result is wrong

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/prez#76]
When running a query, the result is returning with results from previous results of the same query.

I feel like it's probably a caching logic issue where we are repeatedly adding the result to the cache.

Example:

Prez instance: https://d34tz48z3oqfi8.cloudfront.net/#/sparql

Run the following query:

```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT (COUNT(?c) AS ?count)
WHERE {
    ?c a skos:Concept .
}
```

Each time you run the query, it will get the result back along with all the other times this query was run.

**Comment by recalcitrantsupplant** [comment]
there shouldn't be any caching

the FE or yasgui is adding a comment in the first line of the SPARQL query that gets sent, which seems to not be handled by Fuseki.

Compare: 50 results ("# application/sparql-results+json") on first line of sparql query

https://d1sx2k22urhvtf.cloudfront.net/s/sparql?query=%23%20application%2Fsparql-results%2Bjson%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20%2A%20WHERE%20%7B%0A%20%20%3Fsub%20%3Fpred%20%3Fobj%20.%0A%7D%20LIMIT%2010

no comment: 10 results - no comment

https://d1sx2k22urhvtf.cloudfront.net/s/sparql?query=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%20PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%20SELECT%20%2A%20WHERE%20%7B%20%3Fsub%20%3Fpred%20%3Fobj%20.%20%7D%20LIMIT%2010

Not sure why the comment is getting added (don't think specifying a mediatype as a comment is part of the spec), but also not sure why it doesn't appear to be handled (ignored) by Fuseki.
Will come back to this

**Comment by edmondchuc** [comment]
This original issue was reported with usage on the `all` endpoint. There appears to be inconsistent/wrong results when querying on the individual subsystem endpoints as well.

Prez instance: https://gsq-prez.dev.kurrawong.ai/sparql

Query:

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {
  ?sub ?pred ?obj .
} LIMIT 10
```

`all` endpoint:
- as described above, adds 10 rows for every request

`vocprez` endpoint:
- appears to be correct results and respects sparql `limit`

`spaceprez` endpoint:
- same behaviour as `vocprez` endpoint but does not respect sparql `limit`. 
- always returns the largest result rows from previous queries
- result looks wrong, for example, if `limit` is set to 10, and previously it's been set to 30, it returns 30 rows, but with the actual 10 rows tripled.

`catprez` endpoint:
- didn't test since catprez is not enabled for the above Prez instance
