### ISSUE TITLE
Prez curie implementation discussions

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/prez#78]
Hi @recalcitrantsupplant, a couple of initial comments based on the curie implementation mvp made in https://github.com/RDFLib/prez/commit/028c494dbf48e8dc5c4982ce7e369cbca4247d03.

Why is the default separator used for a curie a `-` and not `:`?

`http://www.w3.org/2004/02/skos/core#prefLabel` -> `skos-prefLabel`

versus

`http://www.w3.org/2004/02/skos/core#prefLabel` -> `skos:prefLabel`

---

A generic method of generating curies for unknown namespaces:
- `https://linked.data.gov.au/dataset/qldgeofeatures/BelyandoBasin` -> `ns0:BelyandoBasin`
- `https://linked.data.gov.au/dataset/qldgeofeatures` -> `ns1:qldgeofeatures`
- `https://linked.data.gov.au/def/qg-sites/400GeorgeSt` -> `ns2:400GeorgeSt`

Basically the same behaviour as RDFLib.

Suggestion: Maybe Prez users can declare these unknown or uncommon namespaces using the properties from [VANN](https://vocab.org/vann/).

Example:

```turtle
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix vann: <http://purl.org/vocab/vann/> .

<https://linked.data.gov.au/def/qg-sites> 
    a skos:ConceptScheme ;
    vann:preferredNamespacePrefix "qg-sites" ;
    vann:preferredNamespaceUri "https://linked.data.gov.au/def/qg-sites/" ;
.
```

If the preferred namespace prefix is not declared, then Prez will just generate its own prefix for the namespace like above (`ns0`, `ns1`, etc).

Usage of VANN may be proposed as an optional thing in VocPub and any other relevant profiles for Prez.

**Comment by recalcitrantsupplant** [comment]
Thanks for the feedback,

_Why is the default separator used for a curie a - and not :?_

I researched whether ":" is legal in URLs outside of the scheme - there definitely isn't one consistent opinion. It's at least not clear that different servers would handle it safely. I left it as a parameter in the functions that create/expand the curies, so we could allow setting it via an environment variable as well.

Re. the unknown namespaces, have a look at what I've implemented in the curie_functions.py and reference_data/prefixes/standard.ttl

My thinking was to keep where the prefixes are defined separate from the instance data so as not to impose system requirements on the data.

**Comment by edmondchuc** [comment]
I think `:` is fine in the path segment and query string of URLs. 

I've used it successfully in the past and here's an example service that's using it online. https://prefix.zazuko.com/rdf:type.

The only consideration is with relative URLs where the `:` would be read as the end of the protocol scheme. But I think this situation doesn't apply here.

**Comment by recalcitrantsupplant** [comment]
OK I'll make it configurable so that if there are issues we can opt to substitute it.

The "prez:link" internal links that get generated are relative. Could this cause the issue you're referring to? I guess it depends on how the FE uses the links...

**Comment by edmondchuc** [comment]
I think it'll only cause a problem if it's a relative link that's a curie within an `<a>` element's `href` attribute. 

Example:

```
<a href="prez:link"></a>
```

> OK I'll make it configurable so that if there are issues we can opt to substitute it.

Sounds good!

**Comment by recalcitrantsupplant** [comment]
implemented
