### ISSUE TITLE
CQL search for some data structures broken

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#8]
e.g. https://linked.fsdf.org.au/dataset/placenames/collections/places/items?filter=title%20LIKE%20%22AAD_1000%22 or https://linked.fsdf.org.au/items?filter=title%20LIKE%20%22AAD_1000%22&dataset=placenames&collection=floods,roads,emergmanfacil,medfacil,edufacil,facilities,PS,TL,places,catchments,PSUB

This works (very slowly): https://linked.fsdf.org.au/items?filter=title%20LIKE%20%22coral%22&dataset=electrical-infrastructure&collection=PS

So does this http://idn.kurrawong.net/items?filter=title%20LIKE%20%22Adelaide%22&dataset=AGIL&collection=point-locations

So it's probably that the first working one - elec infra above - is missing a text index and that the non-working one - Placenames - has some differences in data structure??

**Comment by recalcitrantsupplant** [comment]
reimplemented CQL; to reraise if specific issues. Demo instance is online at https://prezv4-with-fuseki.sgraljii8d3km.ap-southeast-2.cs.amazonlightsail.com/docs
