### ISSUE TITLE
SPARQL query request incorrectly adds trailing slash to endpoint URL

### ISSUE THREAD

**Issue by avillar** [RDFLib/prez#95]
The `url=""` line in [methods.py](https://github.com/RDFLib/prez/blob/eb587266591a27fb79ca012a0a34c01539e26aca/prez/sparql/methods.py#L84) is adding a trailing slash to the endpoint URL, resulting in a 404 error for some queries (e.g., for a Fuseki server, `http://localhost:3030/ogc-hosted/update` works, but `http://localhost:3030/ogc-hosted/update/` does not). 

`url=be_endpoint` can be set as a workaround (although it seems a little redundant).

**Comment by avillar** [comment]
This also results in 500 errors when running CONSTRUCT. Can confirm that the workaround does indeed work.

**Comment by edmondchuc** [comment]
Closed in https://github.com/RDFLib/prez/pull/127.
